name: blackfoot_flutter_lint
description: Recommended lints for Blackfoot's Flutter apps to encourage good coding practices.
repository: https://github.com/blackfoot-makers/blackfoot_flutter_lint
version: 1.0.6
homepage: https://blackfoot.io

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
