name: Tag package release version

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Read package version
        id: read-version
        uses: blackfoot-makers/flutter-version-number-action@v1.0
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.read-version.outputs.version-number }}
          message: ${{ github.event.head_commit.message }}
