name: Tag package release version

on:
  workflow_run:
    workflows: ["Test Publish plugin"]
    branches: [main]
    types:
      - completed

jobs:
  tag-release:
    if: "!contains(github.event.commits[0].message, 'Version bump v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update minor version
        if: ${{ github.event.label.name != 'major' }}
        run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)$/$1.($2+1)/e' pubspec.yaml
      - name: Update major version
        if: ${{ github.event.label.name == 'major' }}
        run: perl -i -pe 's/^(version:\s+\d+\.)(\d+)(\.)(\d+)$/$1.($2+1).($3).($4-$4)/e' pubspec.yaml

      - name: Read package version
        id: read-version
        uses: blackfoot-makers/flutter-version-number-action@v1.0
      - name: Version bump and tag
        run: |
          git config user.name Thing-leoh Nicolas
          git config user.email nico@blackfoot.io
          git add pubspec.yaml
          git commit -m "Version bump v${{ steps.read-version.outputs.version-number }}"
          git push
          git tag v${{ steps.read-version.outputs.version-number }}
          git push origin v${{ steps.read-version.outputs.version-number }}
