name: Tag package release version

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    env:
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v3
      - name: Update minor version
        if: ${{ github.event.label.name != 'major' }}
        run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)$/$1.($2+1)/e' pubspec.yaml
      - name: Update major version
        if: ${{ github.event.label.name == 'major' }}
        run: perl -i -pe 's/^(version:\s+\d+\.)(\d+)(\.)(\d+)$/$1.($2+1).($3).($4-$4)/e' pubspec.yaml

      - name: Read package version
        id: read-version
        uses: blackfoot-makers/flutter-version-number-action@v1.0
      - name: Update version bump
        run: |
          git config user.name Thing-leoh Nicolas
          git config user.email nico@blackfoot.io
          git add pubspec.yaml
          git commit -m "[skip ci] Version bump v${{ steps.read-version.outputs.version-number }}"
          git push
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.read-version.outputs.version-number }}
          message: $COMMIT_MESSAGE
