name: Tag package release version

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    if: "!contains(github.event.commits[0].message, 'Version bump v')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Read old package version
        id: read-before-version
        uses: blackfoot-makers/flutter-version-number-action@v1.0
      - uses: actions-ecosystem/action-get-merged-pull-request@v1
        id: get-merged-pull-request
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update minor version
        if: "contains(steps.get-merged-pull-request.outputs.labels, 'minor')"
        run: perl -i -pe 's/^(version:\s+\d+\.\d+\.)(\d+)$/$1.($2+1)/e' pubspec.yaml
      - name: Update major version
        if: "contains(steps.get-merged-pull-request.outputs.labels, 'major')"
        run: perl -i -pe 's/^(version:\s+\d+\.)(\d+)(\.)(\d+)$/$1.($2+1).($3).($4-$4)/e' pubspec.yaml
      - name: Update main version
        if: "contains(steps.get-merged-pull-request.outputs.labels, 'main')"
        run: perl -i -pe 's/^(version:\s+)(\d+)(\.)(\d+)(\.)(\d+)$/$1.($2+1).($3).($4-$4).($5).($6-$6)/e' pubspec.yaml

      - name: Read new package version
        id: read-version
        uses: blackfoot-makers/flutter-version-number-action@main
      - name: Set latest tag
        run: |
          git tag -f latest HEAD
          git push --force origin latest
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: v${{ steps.read-before-version.outputs.version-number }}
          toTag: latest
          failOnError: true
          configurationJson: |
            {
              "template": "#{{UNCATEGORIZED}}\n"
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update CHANGELOG
        run: |
          echo -e "## $PACKAGE_VERSION\n\n$CHANGELOG_FILE$(cat CHANGELOG.md)" > CHANGELOG.md
        env:
          CHANGELOG_FILE: ${{ steps.build_changelog.outputs.changelog }}
          PACKAGE_VERSION: ${{ steps.read-version.outputs.version-number }}
      - name: Version bump and tag
        run: |
          git config user.name Thing-leoh Nicolas
          git config user.email nico@blackfoot.io
          git add pubspec.yaml CHANGELOG.md
          git commit -m "Version bump v$PACKAGE_VERSION"
          git tag "v$PACKAGE_VERSION"
          git push --atomic origin main "v$PACKAGE_VERSION"
        env:
          PACKAGE_VERSION: ${{ steps.read-version.outputs.version-number }}
